# Generated by Django 3.2.4 on 2021-07-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='posted_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='tweet',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='created_on',
        ),
    ]
